import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"], // Adjust this if you need support for more languages
  weight: ["400", "500", "700"], // Add required font weights
  variable: "--font-roboto", // Optional: define a custom CSS variable
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
  s;
}
